# Generated by Django 3.0 on 2019-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191217_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
