# Generated by Django 3.0 on 2019-12-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20191217_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dose',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='recipes.Recipe'),
        ),
    ]
